[build]
builder = "nixpacks"
buildCommand = "npm install -g pnpm && pnpm install --no-frozen-lockfile && pnpm run build"

[build.nixpacksConfig]
noInstallPhase = true

[deploy]
startCommand = "pnpm run start"