import type { TripTemplate } from "@workspace/api-zod";

const enc = (s: string) => encodeURIComponent(s);

const aff = (provider: string, dest: string, label: string) => {
  const d = enc(dest);
  const url =
    provider === "Booking"
      ? `https://www.booking.com/searchresults.html?ss=${d}`
      : provider === "Airbnb"
        ? `https://www.airbnb.it/s/${d}/homes`
        : provider === "GetYourGuide"
          ? `https://www.getyourguide.it/s/?q=${d}`
          : provider === "Viator"
            ? `https://www.viator.com/searchResults/all?text=${d}`
            : provider === "TheFork"
              ? `https://www.thefork.it/ricerca?searchText=${d}`
              : provider === "Trainline"
                ? `https://www.trainline.com/it/search?destination=${d}`
                : `https://www.skyscanner.it/transport/voli-per/${d.toLowerCase()}/`;
  return { provider, label, url } as const;
};

export const TRIP_TEMPLATES: TripTemplate[] = [
  {
    slug: "barcellona-3-giorni-low-budget",
    title: "3 giorni a Barcellona, in due, low budget",
    subtitle: "Tapas, Gaudí e tramonti dal Bunkers del Carmel",
    heroEmoji: "🇪🇸",
    coverPhotoQuery: "barcelona sagrada familia",
    itinerary: {
      title: "Barcellona Slow & Low",
      destination: "Barcellona, Spagna",
      durationDays: 3,
      vibe: "Vivace, mediterranea, accessibile",
      totalBudget: "€480 totali (per 2)",
      bestSeason: "Aprile a Giugno · Settembre a Ottobre",
      heroEmoji: "🇪🇸",
      days: [
        {
          day: 1,
          title: "Gòtic e mare",
          summary: "Atterraggio rilassato, passeggiata nel cuore antico, primo aperitivo sul porto.",
          weather: "Soleggiato 22°C",
          activities: [
            {
              time: "14:00",
              title: "Check-in Hostel One Ramblas",
              description: "Ostello centrale e curato, terrazza sul tetto. Perfetto per non sforare il budget.",
              category: "stay",
              estimatedCost: "€38 a notte a persona",
              coordinates: { lat: 41.3784, lng: 2.1726 },
              photoQuery: "barcelona old town",
              affiliate: aff("Booking", "Barcelona", "Prenota su Booking"),
            },
            {
              time: "16:00",
              title: "Passeggiata nel Barrio Gòtic",
              description: "Vicoli stretti, Plaça Reial, la Cattedrale e una sosta caffè da Caelum.",
              category: "sightseeing",
              estimatedCost: "Gratis",
              coordinates: { lat: 41.3833, lng: 2.1764 },
              photoQuery: "barcelona gothic quarter",
            },
            {
              time: "20:00",
              title: "Cena tapas da Bar del Pla",
              description: "Tapas creative a prezzi onesti vicino al Born. Prendi le carrilleras de cerdo.",
              category: "food",
              estimatedCost: "€22 a persona",
              coordinates: { lat: 41.3853, lng: 2.1813 },
              photoQuery: "barcelona tapas bar",
              affiliate: aff("TheFork", "Barcelona", "Prenota su TheFork"),
            },
          ],
        },
        {
          day: 2,
          title: "Gaudí e Gràcia",
          summary: "Una giornata dedicata al genio modernista, chiusa con un tramonto dal Bunker.",
          weather: "Soleggiato 24°C",
          activities: [
            {
              time: "09:30",
              title: "Sagrada Família (entrata anticipata)",
              description: "Prenota in anticipo: la luce del mattino sulle vetrate è memorabile.",
              category: "experience",
              estimatedCost: "€26 a persona",
              coordinates: { lat: 41.4036, lng: 2.1744 },
              photoQuery: "sagrada familia interior",
              affiliate: aff("GetYourGuide", "Sagrada Familia Barcelona", "Salta la fila"),
            },
            {
              time: "13:00",
              title: "Pranzo al Mercat de la Llibertat",
              description: "Tortilla, jamón e vino della casa al Bar Quim. Atmosfera locale a Gràcia.",
              category: "food",
              estimatedCost: "€15 a persona",
              coordinates: { lat: 41.4022, lng: 2.1545 },
              photoQuery: "barcelona mercat market",
            },
            {
              time: "16:00",
              title: "Park Güell zona libera",
              description: "La parte monumentale è a pagamento, ma i sentieri panoramici sono gratis.",
              category: "sightseeing",
              estimatedCost: "Gratis",
              coordinates: { lat: 41.4145, lng: 2.1527 },
              photoQuery: "park guell barcelona",
              affiliate: aff("GetYourGuide", "Park Guell", "Tour guidato"),
            },
            {
              time: "20:30",
              title: "Tramonto dai Bunkers del Carmel",
              description: "Vista 360° sulla città. Porta una birra dal supermercato, è il rito locale.",
              category: "experience",
              estimatedCost: "€2 birra",
              coordinates: { lat: 41.4181, lng: 2.1592 },
              photoQuery: "bunkers carmel barcelona sunset",
            },
          ],
        },
        {
          day: 3,
          title: "Mare e mercati",
          summary: "Mattina alla Boqueria, pomeriggio in spiaggia, ultima cena con vista.",
          weather: "Sereno 23°C",
          activities: [
            {
              time: "10:00",
              title: "Mercat de la Boqueria",
              description: "Frutta tropicale, jamón ibérico, succhi colorati. Fai colazione qui.",
              category: "food",
              estimatedCost: "€10 a persona",
              coordinates: { lat: 41.382, lng: 2.1717 },
              photoQuery: "boqueria market barcelona",
            },
            {
              time: "13:00",
              title: "Spiaggia di Barceloneta",
              description: "Asciugamano, libro e un pranzo veloce al chiringuito. Mare a 5 minuti dal Born.",
              category: "experience",
              estimatedCost: "Gratis",
              coordinates: { lat: 41.378, lng: 2.1925 },
              photoQuery: "barceloneta beach",
            },
            {
              time: "20:00",
              title: "Paella vista mare a Can Solé",
              description: "Storico ristorante di pesce. Ordinatene una per due, è abbondante.",
              category: "food",
              estimatedCost: "€32 a persona",
              coordinates: { lat: 41.3789, lng: 2.1894 },
              photoQuery: "barcelona paella seafood",
              affiliate: aff("TheFork", "Barceloneta Barcelona", "Prenota su TheFork"),
            },
          ],
        },
      ],
      packingList: [
        { category: "Essenziali", items: ["Documento d'identità", "Carta di credito senza commissioni", "Adattatore EU (opzionale)", "Borraccia"] },
        { category: "Abbigliamento", items: ["Scarpe comode", "Felpa leggera per la sera", "Costume da bagno", "Occhiali da sole"] },
        { category: "Beach kit", items: ["Asciugamano leggero", "Crema solare 30+", "Borsa impermeabile per il telefono"] },
      ],
    },
  },
  {
    slug: "roma-weekend-romantico",
    title: "Weekend romantico a Roma, 2 persone",
    subtitle: "Vespe, gelati al tramonto e cena nel cuore di Trastevere",
    heroEmoji: "🌹",
    coverPhotoQuery: "rome trevi fountain night",
    itinerary: {
      title: "Roma a Due, lentamente",
      destination: "Roma, Italia",
      durationDays: 2,
      vibe: "Romantico, classico, ben mangiato",
      totalBudget: "€680 totali (per 2)",
      bestSeason: "Aprile a Giugno · Settembre a Ottobre",
      heroEmoji: "🌹",
      days: [
        {
          day: 1,
          title: "Centro storico a piedi",
          summary: "Pantheon, Piazza Navona, monetina a Fontana di Trevi e cena nel quartiere ebraico.",
          weather: "Mite 21°C",
          activities: [
            {
              time: "13:00",
              title: "Check-in Hotel Adriano",
              description: "Boutique 4* a 200m dal Pantheon. Stanza con vista sui tetti se chiedi al check-in.",
              category: "stay",
              estimatedCost: "€180 a notte",
              coordinates: { lat: 41.9007, lng: 12.4748 },
              photoQuery: "rome boutique hotel",
              affiliate: aff("Booking", "Roma Centro Storico", "Prenota su Booking"),
            },
            {
              time: "15:30",
              title: "Pantheon e Piazza Navona",
              description: "Inizia dal Pantheon (gratis prenotando online), poi Sant'Ivo alla Sapienza e Navona.",
              category: "sightseeing",
              estimatedCost: "€5 prenotazione Pantheon",
              coordinates: { lat: 41.8986, lng: 12.4769 },
              photoQuery: "pantheon rome",
            },
            {
              time: "18:00",
              title: "Aperitivo da Salotto 42",
              description: "Cocktail bar di design davanti al Tempio di Adriano. Provate il negroni alla cannella.",
              category: "food",
              estimatedCost: "€14 a persona",
              coordinates: { lat: 41.9006, lng: 12.4793 },
              photoQuery: "rome cocktail bar",
            },
            {
              time: "20:30",
              title: "Cena al Ghetto: Nonna Betta",
              description: "Carciofi alla giudia e cacio e pepe nel quartiere ebraico, tra i più affascinanti di Roma.",
              category: "food",
              estimatedCost: "€38 a persona",
              coordinates: { lat: 41.8927, lng: 12.4779 },
              photoQuery: "rome jewish ghetto restaurant",
              affiliate: aff("TheFork", "Roma Ghetto", "Prenota su TheFork"),
            },
          ],
        },
        {
          day: 2,
          title: "Vaticano e Trastevere",
          summary: "Mattina spirituale in Vaticano, pomeriggio lento e cena all'aperto a Trastevere.",
          weather: "Soleggiato 23°C",
          activities: [
            {
              time: "08:30",
              title: "Musei Vaticani salta-fila",
              description: "Apertura mattutina senza folle. Cappella Sistina alla fine del percorso.",
              category: "experience",
              estimatedCost: "€42 a persona",
              coordinates: { lat: 41.9065, lng: 12.4536 },
              photoQuery: "vatican sistine chapel",
              affiliate: aff("GetYourGuide", "Musei Vaticani", "Salta la fila"),
            },
            {
              time: "13:00",
              title: "Pranzo da Bonci Pizzarium",
              description: "La pizza al taglio più famosa di Roma, a due passi dai Musei. Si mangia in piedi.",
              category: "food",
              estimatedCost: "€14 a persona",
              coordinates: { lat: 41.9079, lng: 12.4477 },
              photoQuery: "pizza al taglio rome",
            },
            {
              time: "17:00",
              title: "Tramonto al Gianicolo",
              description: "Salita lenta e gelato da Otaleg. Vista che vi farà rimanere senza parole.",
              category: "sightseeing",
              estimatedCost: "€4 gelato",
              coordinates: { lat: 41.8898, lng: 12.4651 },
              photoQuery: "rome sunset gianicolo",
            },
            {
              time: "20:30",
              title: "Cena a Trastevere: Da Enzo",
              description: "Trattoria romana classica. Niente prenotazione: arrivate alle 19:45 e mettetevi in fila.",
              category: "food",
              estimatedCost: "€32 a persona",
              coordinates: { lat: 41.8878, lng: 12.4732 },
              photoQuery: "trastevere restaurant",
              affiliate: aff("TheFork", "Trastevere Roma", "Cerca alternative su TheFork"),
            },
          ],
        },
      ],
      packingList: [
        { category: "Essenziali", items: ["Carta d'identità", "Pochette per i biglietti museo", "Borraccia (i nasoni di Roma sono gratis)"] },
        { category: "Abbigliamento", items: ["Scarpe da camminata", "Spalle coperte per le chiese", "Maglione leggero per la sera"] },
        { category: "Bonus romantico", items: ["Profumo per la sera", "Polaroid o macchina fotografica", "Lettera per il/la partner"] },
      ],
    },
  },
  {
    slug: "lisbona-4-giorni-mid-budget",
    title: "4 giorni a Lisbona, mid budget",
    subtitle: "Tram 28, pasteis e fado nei vicoli di Alfama",
    heroEmoji: "🇵🇹",
    coverPhotoQuery: "lisbon tram",
    itinerary: {
      title: "Lisbona Lenta",
      destination: "Lisbona, Portogallo",
      durationDays: 4,
      vibe: "Salata, dolce, malinconica",
      totalBudget: "€820 totali (per 2)",
      bestSeason: "Marzo a Giugno · Settembre a Ottobre",
      heroEmoji: "🇵🇹",
      days: [
        {
          day: 1,
          title: "Baixa e tramonto al Miradouro",
          summary: "Piazza del Commercio, Rua Augusta, primi pasteis e tramonto da São Pedro de Alcântara.",
          weather: "Mite 20°C",
          activities: [
            {
              time: "15:00",
              title: "Check-in Memmo Alfama",
              description: "Boutique hotel sopra Alfama, piscina infinity con vista sul Tago. Vale ogni euro.",
              category: "stay",
              estimatedCost: "€190 a notte",
              coordinates: { lat: 38.7115, lng: -9.1305 },
              photoQuery: "lisbon boutique hotel",
              affiliate: aff("Booking", "Lisbona Alfama", "Prenota su Booking"),
            },
            {
              time: "17:00",
              title: "Praça do Comércio e Rua Augusta",
              description: "Sali sul'Arco da Rua Augusta per la prima panoramica della città.",
              category: "sightseeing",
              estimatedCost: "€4 arco",
              coordinates: { lat: 38.7079, lng: -9.1366 },
              photoQuery: "lisbon praca comercio",
            },
            {
              time: "20:00",
              title: "Cena da Taberna da Rua das Flores",
              description: "Cucina portoghese contemporanea, lavagna che cambia ogni sera. Niente prenotazioni.",
              category: "food",
              estimatedCost: "€32 a persona",
              coordinates: { lat: 38.7106, lng: -9.1422 },
              photoQuery: "lisbon portuguese restaurant",
            },
          ],
        },
        {
          day: 2,
          title: "Belém e i pasteis veri",
          summary: "Tutta la giornata dedicata a Belém: monastero, torre e i pasteis originali.",
          weather: "Soleggiato 22°C",
          activities: [
            {
              time: "10:00",
              title: "Mosteiro dos Jerónimos",
              description: "Capolavoro manuelino. Prenota online per saltare la fila.",
              category: "sightseeing",
              estimatedCost: "€10 a persona",
              coordinates: { lat: 38.6979, lng: -9.2068 },
              photoQuery: "jeronimos monastery lisbon",
              affiliate: aff("GetYourGuide", "Belem Lisbon", "Tour Belém"),
            },
            {
              time: "13:00",
              title: "Pasteis de Belém (gli originali)",
              description: "Da provare caldi con cannella e zucchero a velo. Lunga ma scorrevole la fila.",
              category: "food",
              estimatedCost: "€3 a persona",
              coordinates: { lat: 38.6977, lng: -9.2031 },
              photoQuery: "pasteis de belem",
            },
            {
              time: "15:00",
              title: "Torre de Belém e MAAT",
              description: "Foto al simbolo di Lisbona, poi arte contemporanea sul lungofiume al MAAT.",
              category: "sightseeing",
              estimatedCost: "€11 a persona",
              coordinates: { lat: 38.6916, lng: -9.2159 },
              photoQuery: "torre belem lisbon",
            },
          ],
        },
        {
          day: 3,
          title: "Alfama e fado",
          summary: "Tram 28, vicoli di Alfama, miradouros e una serata di fado autentico.",
          weather: "Sereno 21°C",
          activities: [
            {
              time: "10:00",
              title: "Tram 28 da Martim Moniz",
              description: "Saliteci a inizio corsa per assicurarvi un posto al finestrino.",
              category: "transport",
              estimatedCost: "€3 corsa",
              coordinates: { lat: 38.7158, lng: -9.135 },
              photoQuery: "lisbon tram 28",
            },
            {
              time: "12:00",
              title: "Castelo de São Jorge",
              description: "Mura, pavoni e la vista più ampia su Lisbona.",
              category: "sightseeing",
              estimatedCost: "€15 a persona",
              coordinates: { lat: 38.7139, lng: -9.1334 },
              photoQuery: "castelo sao jorge lisbon",
            },
            {
              time: "21:00",
              title: "Fado da Mesa de Frades",
              description: "Ex cappella trasformata in casa di fado. Esperienza intima, prenotare obbligatorio.",
              category: "nightlife",
              estimatedCost: "€55 con cena",
              coordinates: { lat: 38.7136, lng: -9.1289 },
              photoQuery: "fado lisbon alfama",
              affiliate: aff("Viator", "Lisbon Fado", "Trova esperienze di fado"),
            },
          ],
        },
        {
          day: 4,
          title: "Sintra in giornata",
          summary: "Treno regionale fino a Sintra: Pena Palace, Quinta da Regaleira e ritorno per cena.",
          weather: "Mite 19°C",
          activities: [
            {
              time: "09:00",
              title: "Treno per Sintra da Rossio",
              description: "40 minuti di tragitto. Arrivo presto = niente folla al Pena.",
              category: "transport",
              estimatedCost: "€5 andata e ritorno",
              coordinates: { lat: 38.7136, lng: -9.1397 },
              photoQuery: "sintra train station",
              affiliate: aff("Trainline", "Lisbon Sintra", "Cerca treni"),
            },
            {
              time: "10:30",
              title: "Palácio da Pena",
              description: "Castello fiabesco color caramella. Prendete il busetto su, scendete a piedi.",
              category: "experience",
              estimatedCost: "€20 a persona",
              coordinates: { lat: 38.7876, lng: -9.3905 },
              photoQuery: "pena palace sintra",
              affiliate: aff("GetYourGuide", "Sintra Pena Palace", "Salta la fila"),
            },
            {
              time: "14:00",
              title: "Quinta da Regaleira",
              description: "Pozzo iniziatico, grotte e giardini esoterici. Magica.",
              category: "experience",
              estimatedCost: "€15 a persona",
              coordinates: { lat: 38.7964, lng: -9.3962 },
              photoQuery: "quinta regaleira sintra",
            },
            {
              time: "20:30",
              title: "Cena finale al Time Out Market",
              description: "Food hall con i migliori chef di Lisbona. Provate il bacalhau di Henrique Sá Pessoa.",
              category: "food",
              estimatedCost: "€25 a persona",
              coordinates: { lat: 38.7068, lng: -9.1453 },
              photoQuery: "time out market lisbon",
            },
          ],
        },
      ],
      packingList: [
        { category: "Essenziali", items: ["Carta d'identità (no passaporto in UE)", "Lisboa Card opzionale", "Borraccia"] },
        { category: "Abbigliamento", items: ["Scarpe antiscivolo (le calçadas portoghesi sono lisce)", "Giacchetto a vento", "Costume per la piscina dell'hotel"] },
        { category: "Tech", items: ["Power bank", "Adattatore EU", "Cuffie per il treno per Sintra"] },
      ],
    },
  },
  {
    slug: "tokyo-7-giorni-prima-volta",
    title: "7 giorni a Tokyo, prima volta",
    subtitle: "Shibuya, mercati di pesce, ryokan e gita a Hakone",
    heroEmoji: "🗼",
    coverPhotoQuery: "tokyo shibuya night",
    itinerary: {
      title: "Tokyo per la Prima Volta",
      destination: "Tokyo, Giappone",
      durationDays: 7,
      vibe: "Iperstimolante, ordinata, deliziosa",
      totalBudget: "€2.400 totali (per 2)",
      bestSeason: "Marzo a Maggio · Ottobre a Novembre",
      heroEmoji: "🗼",
      days: [
        {
          day: 1,
          title: "Atterraggio a Shinjuku",
          summary: "Recupero dal jet lag, prima nottata nelle luci di Shinjuku.",
          weather: "Mite 18°C",
          activities: [
            {
              time: "16:00",
              title: "Check-in Park Hyatt Tokyo",
              description: "Hotel di Lost in Translation. Camera con vista sul Monte Fuji nelle giornate limpide.",
              category: "stay",
              estimatedCost: "€420 a notte",
              coordinates: { lat: 35.6852, lng: 139.6906 },
              photoQuery: "tokyo shinjuku hotel",
              affiliate: aff("Booking", "Tokyo Shinjuku", "Prenota su Booking"),
            },
            {
              time: "20:00",
              title: "Ramen da Ichiran (Shinjuku)",
              description: "Cabine individuali per concentrarsi sul brodo. Perfetto per il primo pasto.",
              category: "food",
              estimatedCost: "€10 a persona",
              coordinates: { lat: 35.6921, lng: 139.7038 },
              photoQuery: "tokyo ramen ichiran",
            },
          ],
        },
        {
          day: 2,
          title: "Shibuya e Harajuku",
          summary: "Lo Shibuya Crossing, i giovani di Harajuku e il santuario Meiji nascosto nel verde.",
          weather: "Soleggiato 20°C",
          activities: [
            {
              time: "10:00",
              title: "Meiji Jingu",
              description: "Santuario shintoista immerso in 100.000 alberi. Inizia da qui per centrare la mente.",
              category: "sightseeing",
              estimatedCost: "Gratis",
              coordinates: { lat: 35.6764, lng: 139.6993 },
              photoQuery: "meiji shrine tokyo",
            },
            {
              time: "13:00",
              title: "Pranzo a Harajuku: Afuri",
              description: "Ramen yuzu shio, agrumato e leggero. Indimenticabile.",
              category: "food",
              estimatedCost: "€12 a persona",
              coordinates: { lat: 35.6694, lng: 139.7083 },
              photoQuery: "tokyo harajuku ramen",
            },
            {
              time: "18:00",
              title: "Shibuya Crossing dal Mag's Park",
              description: "Salite sul rooftop del Magnet by Shibuya 109 per la foto dall'alto dell'incrocio più famoso.",
              category: "experience",
              estimatedCost: "€5 a persona",
              coordinates: { lat: 35.6595, lng: 139.7004 },
              photoQuery: "shibuya crossing tokyo",
            },
          ],
        },
        {
          day: 3,
          title: "Tsukiji e Ginza",
          summary: "Mercato di pesce esterno all'alba, sushi a colazione, lusso a Ginza.",
          weather: "Soleggiato 21°C",
          activities: [
            {
              time: "07:30",
              title: "Tsukiji Outer Market",
              description: "Strada dello street food più conosciuta del Giappone. Tamago caldo, ostriche grigliate, uni.",
              category: "food",
              estimatedCost: "€20 a persona",
              coordinates: { lat: 35.6655, lng: 139.7707 },
              photoQuery: "tsukiji market tokyo",
            },
            {
              time: "11:00",
              title: "TeamLab Planets",
              description: "Esperienza immersiva di arte digitale. Prenotare con largo anticipo.",
              category: "experience",
              estimatedCost: "€25 a persona",
              coordinates: { lat: 35.6498, lng: 139.7902 },
              photoQuery: "teamlab planets tokyo",
              affiliate: aff("GetYourGuide", "Tokyo Teamlab", "Prenota online"),
            },
            {
              time: "20:00",
              title: "Sushi omakase da Ginza Onodera",
              description: "Stella Michelin. Bancone di 8 posti, esperienza di 2 ore.",
              category: "food",
              estimatedCost: "€180 a persona",
              coordinates: { lat: 35.6717, lng: 139.764 },
              photoQuery: "tokyo sushi omakase",
              affiliate: aff("TheFork", "Tokyo Ginza Sushi", "Cerca su TheFork"),
            },
          ],
        },
        {
          day: 4,
          title: "Asakusa e Akihabara",
          summary: "Tokyo tradizionale al mattino, Tokyo nerd al pomeriggio.",
          weather: "Sereno 22°C",
          activities: [
            {
              time: "10:00",
              title: "Senso-ji Temple",
              description: "Il tempio più antico di Tokyo. Provate la fortuna omikuji.",
              category: "sightseeing",
              estimatedCost: "Gratis",
              coordinates: { lat: 35.7148, lng: 139.7967 },
              photoQuery: "senso-ji tokyo asakusa",
            },
            {
              time: "15:00",
              title: "Akihabara Electric Town",
              description: "Manga, retrogaming, gachapon. Salite all'8° piano del Mandarake.",
              category: "experience",
              estimatedCost: "Variabile",
              coordinates: { lat: 35.7022, lng: 139.7745 },
              photoQuery: "akihabara tokyo",
            },
          ],
        },
        {
          day: 5,
          title: "Gita a Hakone",
          summary: "Onsen, Monte Fuji e ryokan tradizionale per una notte.",
          weather: "Fresco 15°C",
          activities: [
            {
              time: "08:00",
              title: "Treno Romance Car per Hakone-Yumoto",
              description: "85 minuti panoramici. Comprate il Hakone Free Pass alla stazione di Shinjuku.",
              category: "transport",
              estimatedCost: "€42 a persona",
              coordinates: { lat: 35.689, lng: 139.7005 },
              photoQuery: "hakone train japan",
              affiliate: aff("Trainline", "Tokyo Hakone", "Prenota i treni"),
            },
            {
              time: "15:00",
              title: "Check-in Ryokan Gora Kadan",
              description: "Ryokan storico con onsen privati. Cena kaiseki inclusa.",
              category: "stay",
              estimatedCost: "€480 a notte (cena inclusa)",
              coordinates: { lat: 35.2453, lng: 139.0535 },
              photoQuery: "hakone ryokan onsen",
              affiliate: aff("Booking", "Hakone Ryokan", "Cerca su Booking"),
            },
          ],
        },
        {
          day: 6,
          title: "Hakone e ritorno",
          summary: "Crociera sul lago Ashi con vista Fuji, ritorno serale a Tokyo.",
          weather: "Sereno 16°C",
          activities: [
            {
              time: "10:00",
              title: "Crociera sul Lago Ashi",
              description: "Galeone d'epoca con vista sul Monte Fuji nelle giornate limpide.",
              category: "experience",
              estimatedCost: "€15 a persona",
              coordinates: { lat: 35.2086, lng: 139.0258 },
              photoQuery: "lake ashi hakone fuji",
              affiliate: aff("GetYourGuide", "Hakone Lake Ashi", "Prenota la crociera"),
            },
            {
              time: "20:30",
              title: "Yakitori a Shinjuku Omoide Yokocho",
              description: '"Vicolo dei ricordi": minuscoli locali di yakitori del dopoguerra. Spuntini, birra, fumo.',
              category: "food",
              estimatedCost: "€25 a persona",
              coordinates: { lat: 35.6928, lng: 139.6996 },
              photoQuery: "omoide yokocho tokyo",
            },
          ],
        },
        {
          day: 7,
          title: "Ueno e ultima cena",
          summary: "Musei nel parco di Ueno, ultimo giro per regali e cena conclusiva.",
          weather: "Mite 19°C",
          activities: [
            {
              time: "10:00",
              title: "Tokyo National Museum",
              description: "Il museo più importante del Giappone. Sezione spade samurai imperdibile.",
              category: "sightseeing",
              estimatedCost: "€8 a persona",
              coordinates: { lat: 35.7188, lng: 139.7766 },
              photoQuery: "tokyo national museum",
            },
            {
              time: "14:00",
              title: "Ameyoko Market",
              description: "Mercato vivace per ultimi acquisti: kit kat strani, tè matcha, ceramiche.",
              category: "food",
              estimatedCost: "€20 a persona",
              coordinates: { lat: 35.7104, lng: 139.7745 },
              photoQuery: "ameyoko market tokyo",
            },
            {
              time: "20:00",
              title: "Cena finale: Tonkatsu Maisen",
              description: "Il tonkatsu più morbido di Tokyo. Ordinate il filetto kurobuta.",
              category: "food",
              estimatedCost: "€25 a persona",
              coordinates: { lat: 35.6651, lng: 139.7113 },
              photoQuery: "tokyo tonkatsu",
              affiliate: aff("TheFork", "Tokyo Aoyama", "Cerca alternative"),
            },
          ],
        },
      ],
      packingList: [
        { category: "Documenti", items: ["Passaporto valido 6+ mesi", "JR Pass (acquistato online prima della partenza)", "Suica/Pasmo IC card all'arrivo"] },
        { category: "Abbigliamento", items: ["Scarpe da camminata leggere (15-20km al giorno)", "Calze pulite (entrate scalzi nei templi)", "Giacca leggera"] },
        { category: "Tech", items: ["Pocket WiFi o eSIM", "Adattatore JP (presa A)", "App: Google Maps, Google Translate offline"] },
        { category: "Yen", items: ["Contanti (molti locali non accettano carta)", "Borsellino piccolo per le monete da 500"] },
      ],
    },
  },
];
